[package]
name = "creature-simulation"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
crossterm = "0.25.0"
log = "0.4.17"
log4rs = "1.2.0"
rand = "0.8.5"
tui = "0.19.0"
